src/java/jpa/entities/Nota.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpa.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Windows
 */
@Entity
@Table(name = "nota")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Nota.findAll", query = "SELECT n FROM Nota n"),
    @NamedQuery(name = "Nota.findByIdNota", query = "SELECT n FROM Nota n WHERE n.idNota = :idNota"),
    @NamedQuery(name = "Nota.findByNota", query = "SELECT n FROM Nota n WHERE n.nota = :nota")})
public class Nota implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "id_nota")
    private Integer idNota;
    @Basic(optional = false)
    @NotNull
    @Column(name = "nota")
    private int nota;
    @JoinColumn(name = "id_estudiantes", referencedColumnName = "id_estudiantes")
    @ManyToOne
    private Estudiantes idEstudiantes;
    @JoinColumn(name = "id_quiz", referencedColumnName = "id_quiz")
    @ManyToOne
    private Quiz idQuiz;

    public Nota() {
    }

    public Nota(Integer idNota) {
        this.idNota = idNota;
    }

    public Nota(Integer idNota, int nota) {
        this.idNota = idNota;
        this.nota = nota;
    }

    public Integer getIdNota() {
        return idNota;
    }

    public void setIdNota(Integer idNota) {
        this.idNota = idNota;
    }

    public int getNota() {
        return nota;
    }

    public void setNota(int nota) {
        this.nota = nota;
    }

    public Estudiantes getIdEstudiantes() {
        return idEstudiantes;
    }

    public void setIdEstudiantes(Estudiantes idEstudiantes) {
        this.idEstudiantes = idEstudiantes;
    }

    public Quiz getIdQuiz() {
        return idQuiz;
    }

    public void setIdQuiz(Quiz idQuiz) {
        this.idQuiz = idQuiz;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idNota != null ? idNota.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Nota)) {
            return false;
        }
        Nota other = (Nota) object;
        if ((this.idNota == null && other.idNota != null) || (this.idNota != null && !this.idNota.equals(other.idNota))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "jpa.entities.Nota[ idNota=" + idNota + " ]";
    }
    
}

src/java/jsf/NotaController.java
package jsf;

import jpa.entities.Nota;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.sessioneet.NotaFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("notaController")
@SessionScoped
public class NotaController implements Serializable {

    private Nota current;
    private DataModel items = null;
    @EJB
    private jpa.sessioneet.NotaFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public NotaController() {
    }

    public Nota getSelected() {
        if (current == null) {
            current = new Nota();
            selectedItemIndex = -1;
        }
        return current;
    }

    private NotaFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Nota) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Nota();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("resourceerts/Bundle").getString("NotaCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("resourceerts/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Nota) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("resourceerts/Bundle").getString("NotaUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("resourceerts/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Nota) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("resourceerts/Bundle").getString("NotaDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("resourceerts/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Nota getNota(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Nota.class)
    public static class NotaControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            NotaController controller = (NotaController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "notaController");
            return controller.getNota(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Nota) {
                Nota o = (Nota) object;
                return getStringKey(o.getIdNota());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Nota.class.getName());
            }
        }

    }

}

web/nota/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateNotaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateNotaLabel_idNota}" for="idNota" />
                    <h:inputText id="idNota" value="#{notaController.selected.idNota}" title="#{bundle.CreateNotaTitle_idNota}" required="true" requiredMessage="#{bundle.CreateNotaRequiredMessage_idNota}"/>
                    <h:outputLabel value="#{bundle.CreateNotaLabel_nota}" for="nota" />
                    <h:inputText id="nota" value="#{notaController.selected.nota}" title="#{bundle.CreateNotaTitle_nota}" required="true" requiredMessage="#{bundle.CreateNotaRequiredMessage_nota}"/>
                    <h:outputLabel value="#{bundle.CreateNotaLabel_idEstudiantes}" for="idEstudiantes" />
                    <h:selectOneMenu id="idEstudiantes" value="#{notaController.selected.idEstudiantes}" title="#{bundle.CreateNotaTitle_idEstudiantes}" >
                        <f:selectItems value="#{estudiantesController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateNotaLabel_idQuiz}" for="idQuiz" />
                    <h:selectOneMenu id="idQuiz" value="#{notaController.selected.idQuiz}" title="#{bundle.CreateNotaTitle_idQuiz}" >
                        <f:selectItems value="#{quizController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{notaController.create}" value="#{bundle.CreateNotaSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{notaController.prepareList}" value="#{bundle.CreateNotaShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateNotaIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/nota/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditNotaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditNotaLabel_idNota}" for="idNota" />
                    <h:inputText id="idNota" value="#{notaController.selected.idNota}" title="#{bundle.EditNotaTitle_idNota}" required="true" requiredMessage="#{bundle.EditNotaRequiredMessage_idNota}"/>
                    <h:outputLabel value="#{bundle.EditNotaLabel_nota}" for="nota" />
                    <h:inputText id="nota" value="#{notaController.selected.nota}" title="#{bundle.EditNotaTitle_nota}" required="true" requiredMessage="#{bundle.EditNotaRequiredMessage_nota}"/>
                    <h:outputLabel value="#{bundle.EditNotaLabel_idEstudiantes}" for="idEstudiantes" />
                    <h:selectOneMenu id="idEstudiantes" value="#{notaController.selected.idEstudiantes}" title="#{bundle.EditNotaTitle_idEstudiantes}" >
                        <f:selectItems value="#{estudiantesController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditNotaLabel_idQuiz}" for="idQuiz" />
                    <h:selectOneMenu id="idQuiz" value="#{notaController.selected.idQuiz}" title="#{bundle.EditNotaTitle_idQuiz}" >
                        <f:selectItems value="#{quizController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{notaController.update}" value="#{bundle.EditNotaSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditNotaViewLink}"/>
                <br />
                <h:commandLink action="#{notaController.prepareList}" value="#{bundle.EditNotaShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditNotaIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/nota/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListNotaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListNotaEmpty}" rendered="#{notaController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{notaController.items.rowCount > 0}">
                    <h:outputText value="#{notaController.pagination.pageFirstItem + 1}..#{notaController.pagination.pageLastItem + 1}/#{notaController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{notaController.previous}" value="#{bundle.Previous} #{notaController.pagination.pageSize}" rendered="#{notaController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{notaController.next}" value="#{bundle.Next} #{notaController.pagination.pageSize}" rendered="#{notaController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{notaController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListNotaTitle_idNota}"/>
                            </f:facet>
                            <h:outputText value="#{item.idNota}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListNotaTitle_nota}"/>
                            </f:facet>
                            <h:outputText value="#{item.nota}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListNotaTitle_idEstudiantes}"/>
                            </f:facet>
                            <h:outputText value="#{item.idEstudiantes}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListNotaTitle_idQuiz}"/>
                            </f:facet>
                            <h:outputText value="#{item.idQuiz}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{notaController.prepareView}" value="#{bundle.ListNotaViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{notaController.prepareEdit}" value="#{bundle.ListNotaEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{notaController.destroy}" value="#{bundle.ListNotaDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{notaController.prepareCreate}" value="#{bundle.ListNotaCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListNotaIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/nota/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewNotaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewNotaLabel_idNota}"/>
                    <h:outputText value="#{notaController.selected.idNota}" title="#{bundle.ViewNotaTitle_idNota}"/>
                    <h:outputText value="#{bundle.ViewNotaLabel_nota}"/>
                    <h:outputText value="#{notaController.selected.nota}" title="#{bundle.ViewNotaTitle_nota}"/>
                    <h:outputText value="#{bundle.ViewNotaLabel_idEstudiantes}"/>
                    <h:outputText value="#{notaController.selected.idEstudiantes}" title="#{bundle.ViewNotaTitle_idEstudiantes}"/>
                    <h:outputText value="#{bundle.ViewNotaLabel_idQuiz}"/>
                    <h:outputText value="#{notaController.selected.idQuiz}" title="#{bundle.ViewNotaTitle_idQuiz}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{notaController.destroyAndView}" value="#{bundle.ViewNotaDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewNotaEditLink}"/>
                <br />
                <h:commandLink action="#{notaController.prepareCreate}" value="#{bundle.ViewNotaCreateLink}" />
                <br />
                <h:commandLink action="#{notaController.prepareList}" value="#{bundle.ViewNotaShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewNotaIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>